version: '3'

services:
    horizon:
        image: "${APP_DOCKER_STACK}-cli/app:beta-${APP_PHP_VERSION:-8.2}-cli"
        pull_policy: build

        env_file:
            - docker-compose-prod.env

        build:
            context: .
            dockerfile_inline: |
                FROM serversideup/php:beta-${APP_PHP_VERSION:-8.2}-cli

                RUN install-php-extensions gmp
                RUN install-php-extensions intl

                RUN docker-php-serversideup-dep-install-debian gosu

                COPY . /var/www/html

                RUN composer install --no-interaction --prefer-dist --no-scripts \
                && composer dump-autoload --optimize \
                && chown -R www-data:www-data /var/www/html
        
        command: ["gosu", "www-data", "/usr/local/bin/php", "artisan", "horizon"]
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - laravel

networks:
    laravel:
    cloudflared:
        external: true
