version: '3'

services:
    horizon:
        image: "${APP_DOCKER_STACK}-cli/app:php${APP_PHP_VERSION:-8.2}"
        pull_policy: build

        env_file:
            - docker-compose-prod.env

        build:
            context: .
            dockerfile_inline: |
                FROM serversideup/php:${APP_PHP_VERSION:-8.2}-cli

                RUN apt-get update \
                && apt-get install -y --no-install-recommends php${APP_PHP_VERSION:-8.2}-gmp \
                && apt-get clean \
                && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

                COPY . /var/www/html

                RUN composer install --no-interaction --prefer-dist --no-scripts \
                && composer dump-autoload --optimize \
                && chown -R webuser:webgroup /var/www/html
        
        command: ["su", "webuser", "-c", "php artisan horizon"]
        depends_on:
            mysql:
                condition: service_healthy
        networks:
            - laravel

networks:
    laravel:
    cloudflared:
        external: true